- README.md
Closes #
Provide details about your Pull Request and what it adds, fixes or
changes.
> Sonar Test

- README.md
- pom.xml
Closes #
Added src folder to Sonar to see if it makes it analyse the java code. Added badges to readme, because why not.
Might not be the last test with Sonar.
> Sonar test #2

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchReportService.java
Closes #7
Added and populated the interface IBatchReportService
There are no relevant tests to make.
> 7 BatchReportService interface

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Connection.java
- BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/ConnectionTest.java
Closes #11
Added the connection entity class and populated it with fields and methods
> 11 Connection entity class

- BrewMesModulesParent/common_repository/src/main/resources/application.properties
closes #24 
Provide details about your Pull Request and what it adds, fixes or
changes.
> Add repository application.properties file

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/ScheduledBatch.java
- BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/ScheduledBatchTest.java
Closes #15
Added the ScheduledBatch entity class
> 15 ScheduledData entity class

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/MachineData.java
- BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/MachineDataTest.java
Closes #12 
Added the MachineData entity class with its attributes, constructor, getters, and setters. Also wrote test for the methods.
I had to use the //NOSONAR comment to ignore a code smell that didn't like having more than 7 attributes in the constructor.
> 12 MachineData entity class

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchReportService.java
Closes #52 
Added JavaDoc to the method of the interface
> 52 Make JavaDoc for IBatchReportService

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Batch.java
- BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/BatchTest.java
Closes #42
implementation of batch entity 
implementation of batch test
> implement batch entity

- BrewMesModulesParent/common_repository/pom.xml
- BrewMesModulesParent/common_repository/src/main/java/com/brewmes/common_repository/ScheduleRepository.java
Closes #19 
Added the ScheduleRepository interface to save and access objects of ScheduledBatch in the database.
> 19 ScheduleRepository interface

- BrewMesModulesParent/common_repository/pom.xml
- BrewMesModulesParent/common_repository/src/main/java/com/brewmes/common_repository/ConnectionRepository.java
Closes #16
Adds the mongodb repository for the Connection collection
> Add ConnectionRepository

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IScheduleService.java
Closes #10 
Implementation of the IScheduleService. Allows for control of a potential queue system.
> Add ISheduleService

- BrewMesModulesParent/api/pom.xml
- BrewMesModulesParent/batch/pom.xml
- BrewMesModulesParent/common/pom.xml
- BrewMesModulesParent/common_repository/pom.xml
- BrewMesModulesParent/core/pom.xml
- BrewMesModulesParent/livedata/pom.xml
- BrewMesModulesParent/machine/pom.xml
- BrewMesModulesParent/pom.xml
- BrewMesModulesParent/schedule/pom.xml
- BrewMesModulesParent/subscriber/pom.xml
- README.md
Closes #
Fix sonar coverage and made drastic changes to poms
> Sonar coverage

- BrewMesModulesParent/livedata/pom.xml
- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/WebSocketConfig.java
- BrewMesModulesParent/livedata/src/test/java/com/brewmes/livedata/LiveDataControllerTest.java
- BrewMesModulesParent/pom.xml
Closes #26 
In this pr, the LiveDataController and the WebSocketConfig are added.
These give the functionality to read live machine data in the front-end.
> 26 socketmachinedatacontroller

- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfBatchServiceImpl.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfBatchServiceImplTest.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfReportGeneratorTest.java
Closes #36
- Implementation of pdfBatchServiceImpl 
- Update of generatePdf method to take a String path.
> 36 PdfBatchServiceImpl

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
- BrewMesModulesParent/api/src/test/java/com/brewmes/api/MachineControllerTest.java
- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IMachineService.java
Closes #84 
Adds a method in MachineController, so it can return a list of Products.
> 84 make method in the machinecontroller that returns products

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IMachineService.java
Simply changed the name to be more descriptive since we always reference the ID of a Connection object when this is used.
> Change machineID to connectionID

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
Closes #60
Removed the notations
> 60 Remove "required = false" from BatchController

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IScheduleService.java
- BrewMesModulesParent/schedule/pom.xml
- BrewMesModulesParent/schedule/src/main/java/com/brewmes/schedule/ScheduleServiceImpl.java
- BrewMesModulesParent/schedule/src/test/java/com/brewmes/schedule/ScheduleServiceImplTest.java
Closes #29 
This pull request adds functionality to handle the batch queue.
None.
> 29 scheduleserviceimpl

- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfBatchServiceImplTest.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfReportGeneratorTest.java
- BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/MachineData.java
- BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/MachineDataTest.java
Closes #94 
Make state on MachineData an object of MachineState enum
> Make state on MachineData an object of MachineState enum

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
Changes the getProducts endpoint such that it gives a more suitable response.
> Make getProducts return a json object with all the data from the enum

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Connection.java
- BrewMesModulesParent/machine/pom.xml
- BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/AutobrewRunner.java
- BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/MachineServiceImpl.java
- BrewMesModulesParent/machine/src/test/java/com/brewmes/machine/MachineServiceImplTest.java
Closes #32
Add MachineServiceImpl class and an AutoBrewerRunner class which is responsible for running the autobrewer.
New pull request, feel free to give the same feedback if we didn't fix it properly. Lots of stuff was split out so that it should be more manageable now.
> 32 MachineServiceImpl

- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
Apparantly there was another CORS * somewhere which now is making the sonar check on main fail :)
> Add localhost to CORS

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/ScheduleController.java
- BrewMesModulesParent/api/src/test/java/com/brewmes/api/ScheduleControllerTest.java
- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IScheduleService.java
- BrewMesModulesParent/schedule/src/main/java/com/brewmes/schedule/ScheduleServiceImpl.java
- BrewMesModulesParent/schedule/src/test/java/com/brewmes/schedule/ScheduleServiceImplTest.java
Closes #98 
The method now returns a boolean value since the actual position was not used and didn't work as intended.
> 98 Change addToQueue to return boolean

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/util/Products.java
Closes #108 
Adds optimalSpeed to the Products Enum class
> Add optimalSpeed to Products

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
- BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/MachineServiceImpl.java
Closes #85
We decided to remove all the required = false that were left, seeing as they are no longer needed
> 85 Remove 'required = false' from the Machine package

- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PrepareData.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/BatchGetterImplTest.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/DashboardBatchServiceImplTest.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfBatchServiceImplTest.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PdfReportGeneratorTest.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PrepareDataTest.java
- BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/Batch.java
- BrewMesModulesParent/common/src/main/java/com/brewmes/common/util/Products.java
- BrewMesModulesParent/common/src/test/java/com/brewmes/common/entities/BatchTest.java
- BrewMesModulesParent/common/src/test/java/com/brewmes/common/util/ProductsTest.java
- BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java
Closes #104
Provide details about your Pull Request and what it adds, fixes or
changes.
> 104 Make Batch use product enum

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/entities/ScheduledBatch.java
Closes #116 
Changed the datatype such that it is possible to request scheduled batches with double values from the front-end without getting 400 response.
> Change datatype

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
Closes #114 
Add the variable to the json object that is returned
> Add optimal speed to endpoint

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
- BrewMesModulesParent/api/src/main/java/com/brewmes/api/MachineController.java
Closes #110 #112
Fixes missing http header on some endpoints
> 110 products endpoint does not return response entity with json header 

- BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/AutobrewRunner.java
Closes #113
Fixes the NullPointerException 
> 113 NullPointerException in MachineService

- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/WebSocketConfig.java
> Update websocket access

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
- BrewMesModulesParent/api/src/test/java/com/brewmes/api/BatchControllerTest.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/BatchGetterImpl.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/BatchGetterImplTest.java
- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchGetterService.java
Closes #125
Fixes so that we return the page instead of the pages content
> 125 Optimisation of pagination

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
- BrewMesModulesParent/api/src/test/java/com/brewmes/api/BatchControllerTest.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/BatchGetterImpl.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/BatchGetterImplTest.java
- BrewMesModulesParent/common/pom.xml
- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchGetterService.java
- BrewMesModulesParent/common_repository/src/main/java/com/brewmes/common_repository/BatchRepository.java
Closes #127 
Added so it's possible to access batch data from the liveview
> Add access to batch data in liveview

- .github/workflows/integration.yml
- integrationTest/testFiles/collection.json
- integrationTest/testFiles/dummytest.json
- integrationTest/testFiles/test.js
Closes #
- This is a fix for the CI test, to make it fail when the newman test fails.
- Updates assertion on some endpoints
- Removes unwanted autobrew start from the test
> Integrationtest fix

- BrewMesModulesParent/machine/src/main/java/com/brewmes/machine/AutobrewRunner.java
Closes #
Changed how the method flows. This allows for the subscription to be slow or potentially never happen. 
> Fix nullpointer in auto brew runner

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
- BrewMesModulesParent/api/src/main/java/com/brewmes/api/ScheduleController.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/BatchGetterImpl.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/DashboardBatchServiceImpl.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfBatchServiceImpl.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/IBatchReportService.java
- BrewMesModulesParent/schedule/src/main/java/com/brewmes/schedule/ScheduleServiceImpl.java
Closes #136 
Changed access modifier to private on Autowired fields. 
Bonus: removed a public modifier in an interface.
> Set access modifiers private

- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
- BrewMesModulesParent/livedata/src/test/java/com/brewmes/livedata/LiveDataControllerTest.java
Closes #146 
Keeps naming convention consistent.
> Fix method capitalization

- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/DataOverTime.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
- BrewMesModulesParent/batch/src/test/java/com/brewmes/batch/PrepareDataTest.java
> Fixed oee and added rounding to all relevant values

- BrewMesModulesParent/common/src/main/java/com/brewmes/common/services/ILiveDataService.java
- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataController.java
- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataPublisher.java
- BrewMesModulesParent/livedata/src/main/java/com/brewmes/livedata/LiveDataServiceImpl.java
- BrewMesModulesParent/livedata/src/test/java/com/brewmes/livedata/LiveDataControllerTest.java
- BrewMesModulesParent/livedata/src/test/java/com/brewmes/livedata/LiveDataServiceImplTest.java
- BrewMesModulesParent/subscriber/pom.xml
- BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/MachineSubscriber.java
- BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java
Closes #
Adds a SPI(ILiveDataService)
Adds a implementation of the SPI to publish a MachineData object to the WebSocket 👯 
> Adds a service to publish to the WebSocket

- BrewMesModulesParent/pom.xml
> Remove sonar exclusions

- BrewMesModulesParent/api/src/main/java/com/brewmes/api/ScheduleController.java
- BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/PdfReportGenerator.java
- BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/MachineSubscriber.java
- BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java
- integrationTest/testFiles/collection.json
Fixes some minor naming convention inconcistencies and code smells.
SHOULD ONLY BE MERGED IF THE PULL REQUEST ON FRONT-END IS ALSO ACCEPTED!
SHOULD ONLY BE MERGED IF THE PULL REQUEST ON FRONT-END IS ALSO ACCEPTED!
> code_cleanup
